version: 2.1

orbs:
  terraform: 'circleci/terraform@3.0.1'

jobs:
  lint-test:
    docker:
      - image: cimg/node:14.19
    steps:
      - checkout
      - run:
          name: 'Install dependencies'
          command: 'yarn install'
      - run:
          name: 'Run lint'
          command: 'yarn lint'
      - run:
          name: 'Run tests'
          command: 'yarn test'
  postman-test:
    environment:
      DAL_ENDPOINT: http://localhost:8080/v1/graphql
      DAL_ADMIN_SECRET: admin123
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true
    resource_class: medium
    steps:
      - checkout
      - run:
          name: 'Install Project Node'
          # Machine executor has node 16 installed by default .
          # this installs and forces it to use the correct version.
          command: |
            set +x
            source ~/.bashrc
            nvm install 14.19
            NODE_DIR=$(dirname $(which node))
            echo "export PATH=$NODE_DIR:\$PATH" >> $BASH_ENV
      - run:
          name: 'Install dependencies'
          command: 'yarn install'
      - run:
          name: 'Run server'
          command: 'yarn start'
          background: true
      - run:
          name: 'Check server health'
          # Wait for the server to start responding. We expect Request 200 ok once it starts listening.
          # Tries a limited ammount of wget calls.
          command: |
            for i in {1..25};do wget -T 15 -O- -c http://localhost:8080/healthz && exit 0; sleep 10; done; exit 1
      - run:
          name: Run Postman tests
          command: yarn test:postman
      - run:
          when: always
          name: Stop all services declared in docker-compose.yml
          command: docker-compose down
  build:
    docker:
      - image: cimg/node:14.19
    steps:
      - checkout
      - run:
          name: 'Install dependencies'
          command: 'yarn install'
      - run:
          name: 'Run build layer'
          command: 'yarn build:layer'
      - run:
          name: 'Run build lambda'
          command: 'yarn build:lambda'
      - persist_to_workspace:
          root: .
          paths:
            - dist
            - dist_layer
            - terraform
  validate-plan:
    working_directory: /tmp/project
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          command: >-
            echo "credentials \"app.terraform.io\" {token =
            \"$TERRAFORM_TOKEN\"}" > $HOME/.terraformrc
          name: Create .terraformrc file locally
      - run:
          name: terraform init & validate & plan
          command: |
            terraform -chdir=./terraform init -input=false
            terraform -chdir=./terraform validate
            terraform -chdir=./terraform plan -out tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .
  apply:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          command: >-
            echo "credentials \"app.terraform.io\" {token =
            \"$TERRAFORM_TOKEN\"}" > $HOME/.terraformrc
          name: Create .terraformrc file locally
      - run:
          name: terraform
          command: |
            terraform -chdir=./terraform apply -auto-approve tfapply

workflows:
  lint-test-postman-test-build-validate-plan-apply:
    jobs:
      - lint-test
      - postman-test:
          requires:
            - lint-test
      - build:
          requires:
            - postman-test
      - validate-plan:
          context:
            - AWS-DSR
          requires:
            - build
      - hold-apply:
          type: approval
          requires:
            - validate-plan
          filters:
            branches:
              only:
                - master
      - apply:
          context:
            - AWS-DSR
          requires:
            - hold-apply
