CREATE TABLE "public"."eddi_minute" (
    "serialno" int8 NOT NULL,
    "timestamp" timestamp NOT NULL,
    "noseconds" int4 NOT NULL,
    "exportpower" float4,
    "importpower" float4,
    "genpospw" float4,
    "gennegpw" float4,
    "frequency" float4,
    "heatsink" float4,
    "pt1" float4,
    "pt2" float4,
    "voltage" float4,
    "divloadpower1" float4,
    "divloadpower2" float4,
    "boostloadpower1" float4,
    "boostloadpower2" float4,
    "externalcttype1" int2,
    "externalcttype2" int2,
    "externalctpospower1" float4,
    "externalctpospower2" float4,
    "externalctnegpower1" float4,
    "externalctnegpower2" float4,
    PRIMARY KEY ("serialno","timestamp")
);

CREATE TABLE "public"."zappi_minute" (
    "serialno" int8 NOT NULL,
    "timestamp" timestamp NOT NULL,
    "noseconds" int4 NOT NULL,
    "exportpower" float4,
    "importpower" float4,
    "genpospw" float4,
    "gennegpw" float4,
    "frequency" float4,
    "heatsink" float4,
    "voltage1" float4,
    "voltage2" float4,
    "voltage3" float4,
    "divloadpower1" float4,
    "divloadpower2" float4,
    "divloadpower3" float4,
    "boostloadpower1" float4,
    "boostloadpower2" float4,
    "boostloadpower3" float4,
    "externalcttype1" int2,
    "externalcttype2" int2,
    "externalcttype3" int2,
    "externalctpospower1" float4,
    "externalctpospower2" float4,
    "externalctpospower3" float4,
    "externalctnegpower1" float4,
    "externalctnegpower2" float4,
    "externalctnegpower3" float4,
    PRIMARY KEY ("serialno","timestamp")
);

